project:
  type: website
  resources:
  - shinylive-sw.js

website:
  title: "Sensory Extension Toolkit"
  navbar:
    left:
      - href: index.qmd
        text: "Start here"
      - href: discrimination.qmd
        text: "Discrimination tests"
      - href: tetrad-details.qmd
        text: "Recommended procedure"
      - href: analysis.qmd
        text: "Data analysis"
      - href: app.qmd
        text: "Try it out!"
      - href: about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto

