---
title: "Data analysis for tetrad discrimination tests"
from: markdown+emoji
---

To use this part of the toolkit, you will need the results of your tetrad test.  Specifically, you will need:

*  Your prior intuition for how easy it would be for panelists to tell the difference between the samples.  You wrote this down, right?
*  The number of subjects who participated, which we can call $N$.  
*  The number of subjects *who got the right answer*, which we can call $x$.  By necessity, $x≤N$. 

Once you've got those, we're ready to get analyzing!

## Prior intuitions and expectations

Why do we care about your prior intuitions?  Why do you need to write them down?  In this analysis, we use your expertise, in the form of your **prior expectations**, to improve our statistical analysis.  Simply put, your past observations on experiments--formal or informal--are valuable information, and we're not going to just throw them away.  

The reason we ask you to write down your expectations before you run the test is to separate what you knew before the sensory test from what you learned afterwards.  It's impossible for us to not try to make sense of new knowledge--that's basic reasoning!--so once we run the experiment, we update our prior knowledge with what we just learned.  Therefore, for this analysis, it's important to write down what we thought would happen before we run the test.  We recommend you just write a simple statement down in your lab notebook, indicating whether you think you'll find a difference or not, and whether you're sure or just leaning slightly in that direction.

You might also be thinking that using your expectations will bias the outcome of our experiment.  But, actually, insisting that you can't use your prior knowledge is also biasing.  Without getting into a philosophical argument (you can read a book [like this one](https://bookshop.org/p/books/bernoulli-s-fallacy-statistical-illogic-and-the-crisis-of-modern-science-aubrey-clayton/) for that), think about a typical "null hypothesis" for our Merlot-blending example: in this case, a null hypothesis would be that there is literally zero effect on the flavor, color, aroma, or mouthfeel of your wine from adding a barrel of Merlot to our blend.  In reality, these null hypotheses are never true: different things are different.  

We can assign numerical estimates to our informed opinons--our **expectations**--and you can see a visualization of the choices we've made for this project in the [data analysis tool outputs](app.qmd).

## What you'll get from this data analysis

Before we get to the analysis, a quick, intuitive explanation.  Above, we talked about two important numbers: $x$ and $N$.  In fact, the proportion of correct answers, $x/N$ is the key quantity we're interested in here.  Specifically, we're interested in what insight $x/N$ gives us into the plausible proportion of people noticing a difference in your two products, A and B, which we'll call $\pi$ ($\pi=p=$ proportion).  Because $\pi$ is a proportion $0≤\pi≤1$, but we will present results in terms of both $\pi$ and in terms of the number of people in 100 who would notice a difference.

Intuitively, if $\pi$ is closer to $1$, then most people will notice a difference.  If $\pi$ is closer to $0$, then very few people will.  Behind the scenes, we're using $x/N$, combined with your prior estimate of how likely you think there is to be a *sensory* difference between A and B, to calculate a plausible range of $\pi$ values that could lead to that $x/N$.

By giving some worst- and best-case outcomes, we'll tell you what you should expect to see, based on your prior intuition and your actual data, if you brought your products to market.

## Further Reading

To learn more about the statistical calculations we're making, we recommend [the linked chapter 3 from *Bayes Rules!*](https://www.bayesrulesbook.com/chapter-3), a handbook for Bayesian statistics.  The entire book is available online, making it a great resource for those outside academia:

* Johnson, A. A., Ott, M. Q., & Dogucu, M. (2022). *Bayes rules!: An introduction to applied Bayesian modeling*. Chapman and Hall/CRC.

