---
title: "Discrimination testing"
from: markdown+emoji
---

So far, we've talked about what you can do with a general discrimination test. In fact, there are many specific discrimination tests, all of which involve testing a similar, basic question:

> When samples are presented without identifying information, can panelists identify which sample or samples are different?

Notice that we write "**panelists**" above: a key principle of sensory testing is that no one person, no matter how well-trained or expert, is accurate all the time or for every product. Just because one person notices a difference between samples doesn't mean that everyone (or even most people) will, or that the same person will notice the difference every time.

Therefore, we use a group of subjects to conduct a sensory test, and we use statistics to try to generalize from the results--to update our understanding of the differences (or not!) between the products. This helps avoid drawing wrong conclusions just because someone had an off day or got very lucky.

## Production goals

To tie the abstract discussion above to a concrete production goal, imagine that you're a winemaker, and this year you have an extra barrel of merlot this season that you'd love to be able to use in your Bordeaux blend, but you're not sure if the subsequent change in ratios--maybe closer to 45% instead of 35% merlot--would cause a major overall sensory change.  You can use a discrimination test on bench blends to determine whether, on average, tasters will notice the difference in blends when tasted blind.

## General procedure for conducting a discrimination test

![Presentation of samples for a *tetrad* test on cider samples. This picture presents a key cautionary example: don't give your panelists extra clues about the different sample: here two samples are implied to be the same.[^1]](img/tetrad-test-example.JPG){#badexample width=90%}

In general, a discrimination test requires the following:

*  **Definition of the test objective**: what difference are you trying to quantify?  Ask yourself how sure you are that a difference between the samples will be found. Examining our prior beliefs helps us calibrate the test.
*  **Sample preparation**: anonymize samples and prepare to present them in a consistent fashion
*  **Panelist recruitment**: typically we want at least 20 subjects to participate, and closer to 40 is preferred. In addition, it is usually a good idea to have panelists who do not all work in the winery or cidery--experience leads to expertise with the product.
*  **The test(!)**: present the samples in the appropriate fashion (see below and [next tab](tetrad-details.qmd) for a specific, recommended method), which will involve "anonymizing" samples (masking their identity in a way you can keep track of), and collecting responses in a "ballot".
*  **Analyze the data**: use appropriate statistics (or a toolkit like this one!) to determine what the combination of your prior hypothesis and your observed data tells you about the actual range of possible difference between the two samples.
*  **Make interpretations**: based on the observed results and subsequent statistical output (which typically gives a range of compatible true probabilities of discrimination), determine the risk of accepting that the samples are or are not different.

## The "tetrad" test: Our recommended discrimination test

There are many test procedures that follow the basic steps above, but rather than debate specific use cases or advantages, we are going to simply recommend that wineries and cideries use the **tetrad test** procedure. [For reasons that are beyond the scope of this toolkit](https://www.sensorysociety.org/meetings/2016%20Presentations/W_SM_Kamerud.pdf), the tetrad test is more powerful than comparable tests, and has the advantage of being easy to set up and to present to panelists. We think this makes it ideal for use in a winery or cidery environment

To learn about the tetrad test, please [go on to the next tab](tetrad-details.qmd), where we'll go into detail.

[^1]: Notice the different colors of ink!